In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1[2]

3

In [7]:
arr1[1:4]

array([2, 3, 4])

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2[1][1]

5

In [12]:
arr2[1,1]

5

In [11]:
arr2.shape

(3, 3)

In [14]:
arrR = np.arange(0, 11, 2)
arrR

array([ 0,  2,  4,  6,  8, 10])

In [17]:
arrL = np.linspace(0, 10, 20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [18]:
arrL.shape

(20,)

In [25]:
arrL = arrL.reshape(5, 4)
arrL

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737],
       [ 2.10526316,  2.63157895,  3.15789474,  3.68421053],
       [ 4.21052632,  4.73684211,  5.26315789,  5.78947368],
       [ 6.31578947,  6.84210526,  7.36842105,  7.89473684],
       [ 8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [20]:
arrZ = np.zeros((3, 3))
arrZ

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arrO = np.ones((3, 3))
arrO

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arrR = np.repeat(arrL, 4)
arrR

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.52631579,
        0.52631579,  0.52631579,  0.52631579,  1.05263158,  1.05263158,
        1.05263158,  1.05263158,  1.57894737,  1.57894737,  1.57894737,
        1.57894737,  2.10526316,  2.10526316,  2.10526316,  2.10526316,
        2.63157895,  2.63157895,  2.63157895,  2.63157895,  3.15789474,
        3.15789474,  3.15789474,  3.15789474,  3.68421053,  3.68421053,
        3.68421053,  3.68421053,  4.21052632,  4.21052632,  4.21052632,
        4.21052632,  4.73684211,  4.73684211,  4.73684211,  4.73684211,
        5.26315789,  5.26315789,  5.26315789,  5.26315789,  5.78947368,
        5.78947368,  5.78947368,  5.78947368,  6.31578947,  6.31578947,
        6.31578947,  6.31578947,  6.84210526,  6.84210526,  6.84210526,
        6.84210526,  7.36842105,  7.36842105,  7.36842105,  7.36842105,
        7.89473684,  7.89473684,  7.89473684,  7.89473684,  8.42105263,
        8.42105263,  8.42105263,  8.42105263,  8.94736842,  8.94

In [29]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arrR.size

80

In [31]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1 + 1

array([2, 3, 4, 5, 6])

In [32]:
arr1 * 2

array([ 2,  4,  6,  8, 10])

In [33]:
sum1 = np.sum(arr1, axis=0)
sum1

15

In [35]:
min1 = np.min(arr1)
min1

1

In [36]:
max1 = np.max(arr1)
max1

5

In [37]:
mean1 = np.mean(arr1)
mean1

3.0

In [38]:
median1 = np.median(arr1)
median1

3.0

In [41]:
arr2T = arr2.T
arr2T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
arr2T = arr2T.flatten()

In [45]:
arr2T = np.append(arr2T, [11, 12, 10])
arr2T

array([ 1,  4,  7,  2,  5,  8,  3,  6,  9, 11, 12, 10])

In [46]:
arr2T = np.insert(arr2T, 1, 100)
arr2T

array([  1, 100,   4,   7,   2,   5,   8,   3,   6,   9,  11,  12,  10])

In [48]:
arr2T = np.delete(arr2T, 1)
arr2T

array([ 1,  7,  2,  5,  8,  3,  6,  9, 11, 12, 10])

In [59]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [60]:
arr_cat = np.concatenate((arr1, arr2), axis=0)
arr_cat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr_cat = np.concatenate((arr1, arr2), axis=1)
arr_cat

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [62]:
arr_cat = np.vstack((arr1, arr2))
arr_cat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
arr_cat = np.hstack((arr1, arr2))
arr_cat

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [65]:
arr1 = np.array([[1, 2, 3], [1, 2, 3], [4, 5, 6]])
arr_u = np.unique(arr1)
arr_u

array([1, 2, 3, 4, 5, 6])