In [1]:
import numpy as np

In [2]:
samuel = np.array([73,67,43])

In [3]:
sam = samuel
sam

array([73, 67, 43])

In [4]:
sam[1]

67

In [5]:
type(sam)

numpy.ndarray

In [6]:
sam.sum()

183

In [7]:
sam * 10

array([730, 670, 430])

In [8]:
sam - 20

array([53, 47, 23])

In [9]:
sam

array([73, 67, 43])

In [10]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

In [11]:
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [15]:
%%time
result = 0
for x,y in zip(arr1, arr2):
    result += x*y
result

CPU times: user 615 ms, sys: 0 ns, total: 615 ms
Wall time: 613 ms


833332333333500000

In [16]:
%%time 
np.dot(arr1_np, arr2_np)

CPU times: user 6.53 ms, sys: 216 µs, total: 6.75 ms
Wall time: 5.71 ms


833332333333500000

In [20]:
numbers = np.array([[1,2,3],
                    [4,5,6]])
numbers

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
numbers.shape

(2, 3)

In [22]:
numbers.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])