## Numpy arrays

- array is a collection of a single data type (mainly the int and float data types)

In [1]:
import numpy as np

# Making np arrays

In [38]:
a = np.array([1, 2, 3, 4, 5])
print(a)
a.dtype

[1 2 3 4 5]


dtype('int64')

In [39]:
b = np .array([1, 6, 3, 4, 9])
print(b)
b.dtype

[1 6 3 4 9]


dtype('int64')

In [40]:
c = np.array((1, 2, 3, 4))
print(c)
type(c)

[1 2 3 4]


numpy.ndarray

# Numpy datatypes

In [41]:
a = np.array([1, 2, 3, 4, 5], dtype='i')
a

array([1, 2, 3, 4, 5], dtype=int32)

In [42]:
a.dtype

dtype('int32')

In [43]:
d = np.array([1, 2, 3, 4, 5], dtype='f')
d

array([1., 2., 3., 4., 5.], dtype=float32)

In [44]:
d.dtype

dtype('float32')

# Dimensionality

In [45]:
# 1D
a = np.array(0)
a.ndim

0

In [46]:
# 1D
a = np.array([1, 2, 3, 4, 5])
print(a)
a.ndim

[1 2 3 4 5]


1

In [47]:
a = np.array([1])
a.ndim

1

In [48]:
# 2D
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
b.ndim

[[1 2 3]
 [4 5 6]]


2

In [49]:
# 3D
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(c)
c.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

# Accessing dimensions

In [50]:
a[0]

1

In [51]:
b[0][2]

3

In [52]:
c[1][1][1]

5

# Shape

In [53]:
a.shape

(1,)

In [54]:
b.shape

(2, 3)

In [55]:
print(c.shape)
print(f'Number of 2D are present: {c.shape[0]}')
print(f'Number of 1D are present: {c.shape[1]}')
print(f'Number of elements in 1D: {c.shape[2]}')

(2, 2, 3)
Number of 2D are present: 2
Number of 1D are present: 2
Number of elements in 1D: 3


# Numpy functions

## 1. arange

In [56]:
e = np.arange(100)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
e = np.arange(20, 100)
e

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
e = np.arange(0,100,3)
e

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## 2. random

In [59]:
# permutation creates a random number generator that randomly selects elements

f = np.random.permutation(np.arange(10))
f

array([4, 6, 9, 2, 5, 1, 7, 0, 8, 3])

In [60]:
# random creates a random number generator that randomly

f = np.random.randint(0, 10)
f

3

In [61]:
type(f)

int

In [62]:
# view function code and documentation
np.random.randint??

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [63]:
a = np.random.rand(100)
print(a)

[0.79999143 0.20320559 0.92530779 0.66705931 0.38394907 0.62396957
 0.6494508  0.42581911 0.08875621 0.44108324 0.25998617 0.52102897
 0.92252491 0.19803687 0.73189375 0.05361753 0.11726521 0.80967615
 0.65805808 0.83851469 0.48008955 0.94257539 0.00698891 0.18944294
 0.48914666 0.02640235 0.8623698  0.63371974 0.14814966 0.81310837
 0.71701367 0.71961389 0.35180185 0.98477821 0.89626631 0.36253307
 0.89898982 0.30503631 0.6076103  0.13271122 0.50630127 0.93530466
 0.71815312 0.52227047 0.27791277 0.96401562 0.99462103 0.56636319
 0.14077809 0.42630323 0.42730653 0.03140049 0.26955184 0.19966155
 0.68682816 0.20353479 0.86268609 0.52892568 0.56701484 0.01098815
 0.56833078 0.45959502 0.96161351 0.06805968 0.32687182 0.8552536
 0.08531126 0.77756735 0.8004101  0.99817967 0.3763211  0.08250016
 0.86402651 0.4287992  0.03647137 0.48938527 0.02456423 0.1258836
 0.97442758 0.52342581 0.67709157 0.75087603 0.44970414 0.78458164
 0.70657059 0.35381068 0.55322497 0.3614178  0.83924412 0.362770

In [64]:
a.shape

(100,)

In [65]:
a.reshape(2,50)

array([[0.79999143, 0.20320559, 0.92530779, 0.66705931, 0.38394907,
        0.62396957, 0.6494508 , 0.42581911, 0.08875621, 0.44108324,
        0.25998617, 0.52102897, 0.92252491, 0.19803687, 0.73189375,
        0.05361753, 0.11726521, 0.80967615, 0.65805808, 0.83851469,
        0.48008955, 0.94257539, 0.00698891, 0.18944294, 0.48914666,
        0.02640235, 0.8623698 , 0.63371974, 0.14814966, 0.81310837,
        0.71701367, 0.71961389, 0.35180185, 0.98477821, 0.89626631,
        0.36253307, 0.89898982, 0.30503631, 0.6076103 , 0.13271122,
        0.50630127, 0.93530466, 0.71815312, 0.52227047, 0.27791277,
        0.96401562, 0.99462103, 0.56636319, 0.14077809, 0.42630323],
       [0.42730653, 0.03140049, 0.26955184, 0.19966155, 0.68682816,
        0.20353479, 0.86268609, 0.52892568, 0.56701484, 0.01098815,
        0.56833078, 0.45959502, 0.96161351, 0.06805968, 0.32687182,
        0.8552536 , 0.08531126, 0.77756735, 0.8004101 , 0.99817967,
        0.3763211 , 0.08250016, 0.86402651, 0.4

In [66]:
type(a)

numpy.ndarray

## Slicing

In [2]:
e = np.arange(100)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
e[1:5]

array([1, 2, 3, 4])

In [4]:
e[:5]

array([0, 1, 2, 3, 4])

In [5]:
e[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [6]:
e[2: 100: 3]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [7]:
e[e< 40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [8]:
e[(e<50) & (e>40)]

array([41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
e[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

# Broadcasting

In [74]:
e = e +1
e

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])