## Numpy
- stores on data type for each array
- Deals with numerical data
- 

In [1]:
import numpy as np

## 1

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
# check the data type of items
a.dtype

dtype('int64')

In [8]:
a = np.array([1, 2, 3, 4, 5], dtype='i')
a.dtype

dtype('int32')

## 2

In [5]:
b = np.array((1, 2, 3, 4, 5, 6), dtype='f')
b

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [6]:
type(b)

numpy.ndarray

In [7]:
b.dtype

dtype('float32')

In [9]:
# Dimensions
b.ndim

1

## 3

In [12]:
c = np.array([[1, 2, 3], [2, 5, 7]])
c.ndim

2

In [13]:
# indexing
c[1,1]

5

In [14]:
c[0,1]

2

## 4

In [19]:
d = np.arange(0, 100, 1)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
d.ndim

1

In [24]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])